### ISSUE TITLE
After installing LN+Bitcoin, and when going to remove btc volume,  no warning about the use of the volume by  LN was shown

### ISSUE THREAD

**Issue by Shelpin** [dappnode/DAppNodePackage-bitcoin#10]

**Comment by eduadiez** [comment]
The Lightning package doesn't have any volume dependent on the bitcoin, so it's the expected behavior.

https://github.com/dappnode/DAppNodePackage-LightningNetwork/blob/master/dappnode_package.json

**Comment by Shelpin** [comment]
But the LN package uses the bitcoin node and it contains the bitcoin dependency in the manifesto, anyway it is solved now 

![image](https://user-images.githubusercontent.com/21328788/61186323-276e6f00-a664-11e9-85c9-1fdeb097fa77.png)
