### ISSUE TITLE
Ability to choose the network

### ISSUE THREAD

**Issue by vdo** [dappnode/DAppNodePackage-bitcoin#4]
This package only uses mainnet by default. It would be nice to have an env var to choose testnet so it can be used by the LND package as well

**Comment by Shelpin** [comment]
Also consider having a  btc testnet package running independently so users can use LN in mainet and testnet , we could add  in the bitcoin package info of an ipfs  hash to install it... if you have to stop your btc node to run tests and then go back to mainet and sync again it is not very convenient...  there  are some movement in the development of LApps and it could be very useful important for users to have the opportunity of running mainet and testnet at the same time

**Comment by dapplion** [comment]
@pablomendezroyo @Pol-Lanski Could you review if still makes sense?

**Comment by alexpeterson91** [comment]
Doesnt make sense to allow users to choose the network.  
adding new packages for other configs like testnet or BCH  or something are much better solutions if still desired.
